### PR TITLE
build(deps): restrict codeshield installation to non-Windows platforms

### PR DESCRIPTION
**Pull request by weekenthralling**
[#153]

### CODE REVIEW

**Comment by edwardzjl** [comment]
This is a temporary solution. Ultimately, we may migrate the code-check functionality to a custom IPython kernel.

I'll keep this PR open for a while to assess if the update becomes urgent.

**Comment by edwardzjl** [comment]
This basically breaks all Windows developers.

**Comment by weekenthralling** [comment]
> This basically breaks all Windows developers.这基本上让所有 Windows 开发人员崩溃了。

As you said before, we should not add the code scanning function to tablegpt-agent.

Maybe I should revert the previous commit until I can come up with a better solution?

**Comment by weekenthralling** [comment]
And I tested this scanning function repeatedly and found that it was not as easy to use as he said.

For example, in his documentation, he describes that incomplete code can be detected and a warning can be given.

When I used `print('Hello, World!'` to scan, I found that it did not give a warning

**Comment by edwardzjl** [comment]
I’m not sure, but no matter where we place the `codeshield`, installing local development dependencies will cause it to break on Windows.

I think revert it is the best solution for now.

**Comment by weekenthralling** [comment]
PR #162 has been submitted, so close the current PR

**Pull request closed without merging**
