### PR TITLE
feat: tablegpt kernel setups

### PR DESCRIPTION
**Pull request by zTaoplus**
We should add the custom TableGPT agent IPython kernel to run our code. 
This will address the bug related to custom built-in functions not being found (issue: https://github.com/tablegpt/tablegpt-agent/issues/74).

This feature can be merged once both https://github.com/tablegpt/tablegpt-agent/pull/79 and https://github.com/edwardzjl/pybox/pull/29 are merged and published.

### CODE REVIEW

**Comment by zTaoplus** [comment]
The reason for the CI failure is that PyBox has not yet merged the code and released the latest version.

**Review by edwardzjl — DISMISSED** [review]

**Comment by edwardzjl** [comment]
Pybox 0.0.14 was published

**Comment by edwardzjl** [comment]
Maybe specify `pppybox>=0.0.14` in `pyproject.toml` and try again?

**Comment by zTaoplus** [comment]
Update：

-  Added a missing dependency: langchain-openai.
- Configure the installation of local kernel dependencies as optional.
- pppybox version upgraded to 0.0.14
- Align hatch fmt and pre commit ruff configuration.
- lint

**Comment by edwardzjl** [comment]
LGTM, but does `tablegpt-agent` actually require `langchain-openai`? It seems to be used only in the documentation and examples for illustration purposes.

**Comment by zTaoplus** [comment]
> LGTM, but does `tablegpt-agent` actually require `langchain-openai`? It seems to be used only in the documentation and examples for illustration purposes.

Oh, I didn't consider that. I should add the installation guide for this dependency `langchian-openai` to the doc.

**Review by edwardzjl — APPROVED** [review]
LGTM

**Pull request merged**
